apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
  containers:
  - name: web-server
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
