apiVersion: v1
kind: ReplicationController
metadata:
  name: web-server
spec:
  replicas: 2
  selector:
    name: apache
  template:
    metadata:
      labels:
        name: apache
    spec:
      containers:
      - image: neerjaj2/rollingupdate-apache:v1
        name: apache
        ports:
        - containerPort: 80
          protocol: TCP

