apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-rw
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /srv/www
      name: www-data
  volumes:
  - name: www-data
    emptyDir: {}
