apiVersion: v1
kind: Pod
metadata:
  name: emptydir-readonly
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /srv/www
      name: www-data
      readOnly: true
  volumes:
  - name: www-data
    emptyDir: {}
