apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: asimplewebserver
  name: asimplewebserver
spec:
  replicas: 1
  selector:
    run: asimplewebserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: asimplewebserver
    spec:
      containers:
      - image: nginx
        name: asimplewebserver
        resources: {}
status:
  replicas: 0
