apiVersion: v1
kind: ReplicationController
metadata:
  name: update-demo-app2
spec:
  selector:
    name: update-demo
    version: app2
  template:
    metadata:
      labels:
        name: update-demo
        version: app2
    spec:
      containers:
      - image: neerjaj2/rollingupdate-apache:v2
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP

