---
apiVersion: v1
kind: ReplicationController
metadata:
  name: environment-demo
  labels:
    name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webserver
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: DOCUMENT_ROOT
          value: /var/www/html
        - name: NGINX
          value: v2
